motion_control-objs += abc123_motion.o \
                       fsm.o \
                       hds_host.o \
                       motor_hades_comms.o \
                       abc123_motion_adc.o

obj-$(CONFIG_MOTION_CONTROL) += motion_control.o
